databases:
  - name: saltadev-db
    plan: free
    databaseName: saltadev
    user: saltadev

services:
  - type: redis
    name: saltadev-redis
    plan: free
    ipAllowList: []
    maxmemoryPolicy: allkeys-lru

  - type: web
    plan: free
    name: saltadev-website
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "cd saltadev && gunicorn saltadev.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: saltadev-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: saltadev-redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: saltadev.settings.production
      - key: ALLOWED_HOSTS
        value: ".onrender.com,salta.dev"
      - key: PYTHON_VERSION
        value: "3.12.11"
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: DEFAULT_FROM_EMAIL
        sync: false
      - key: SITE_URL
        sync: false
      - key: RECAPTCHA_V2_SITE_KEY
        sync: false
      - key: RECAPTCHA_V2_SECRET
        sync: false